### ISSUE TITLE
Integration test cases

### ISSUE THREAD

**Issue by jklmnn** [Componolit/capdpa#18]
Create integration test cases that cover the whole process from reading a C++ header to generating an Ada spec from that.

Resulting steps:
- [x] Fix import aspects in generator
- [x] Correctly address tagged Types in Ada (`A::B` -> `A.B.B`)
- [x] handle missing default constructor
- [x] use global namespace
- [x] either resolve types to standard types or use own type package

Finally:
- [x] Integration test cases
- [x] Running integration test

**Comment by jklmnn** [comment]
The current generator test cases had invalid Import aspects. This was fixed with abb1a15928c39f19c88e480fdc394873a3cad487 but the generator needs to be adapted.

Furthermore when using a type consisting of a C++ class, `A::B` does not translate into `A.B` but `A.B.B` as the class type `B` needs to be accessed inside the package `B`. This currently isn't addressed and should be regarded in the generator.

**Comment by senier** [comment]
An idea to fix the class naming issue: In the Ada specification, do not name the record after the class it was created from, but use some fixed name (like `Class_Type`).

**Comment by jklmnn** [comment]
Classes with no explicit constructor do not have a constructor field in clangs AST. So we have to check that each class has at least one constructor and if not we have to generate a default one.

**Comment by jklmnn** [comment]
We need to decide if we want to either use standard types or define our own package (currently `Capdpa.Types`) to define custom types there. The latter option has the benefit that it catches stray typedefs.

**Comment by jklmnn** [comment]
To prevent collisions with other code all generated packages are children of a global or project package. This project package also provides types and objects of the default namespace.

Builtin types are resolved to types of the project package. Typedefs are renames in the according packages.

**Comment by jklmnn** [comment]
Typedefs can be resolved and converted to an Ada specification. As there is only one test yet this needs to be tested more.

**Comment by jklmnn** [comment]
Types are resolved to either their definition location or to the project package that is parent to all generated code.

**Comment by senier** [comment]
Basic tests are done. More tests will be added when new features are added.
