### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jklmnn** [Componolit/capdpa#2]
## Simple tests

The simple approach is to compare generated Ada code with an expected ouput.

Test cases:
 - [ ] empty class
 - [ ] class with scalar class member variables
 - [ ] class with member functions
 - [ ] class with non scalar member variables
 - [ ] class in namespace
 - [ ] namespace in namespace

## Complex tests

To test the test cases the idea is to create one directory per test case which then contains a `C`, an `Ada` and a `run` subdirectory. The `C` directory contains all the C code which should be converted to Ada and `Ada` contains any code that is used to run the test except the converted code itself. On test execution all code is copied to `run` where also the generated Ada code is written to. Then the makefile gets called which compiles the code in run and runs the resulting binary. The test success depends on the resulting exit code (with zero being success).

**Comment by jklmnn** [comment]
Furthermore we should use CI to run the tests automatically. @senier can you enable this on this repo (unless you already did)?

**Comment by senier** [comment]
Done.

**Comment by jklmnn** [comment]
This has become obsolete by #12, #18  and #19.
