### ISSUE TITLE
C++ inheritance

### ISSUE THREAD

**Issue by jklmnn** [Componolit/capdpa#20]
Check how C++ classes that inherit another class behave in clangs AST and if their parents members are available.
If the members are not available it has to be checked how the according Ada package is built.

**Comment by jklmnn** [comment]
The offsets of class members are the offsets of all class members of all parents in their given order. If a parent has a virtual function a vtable is prepended with 8 (4 on 32bit) bytes size.
This vtable is marked with a tagged limited record instead of a limited record.
If no vtable is present the parents members must be included into the child manually as inheritance is not supported in this case.

Showcases:

- [ ] C inherits from P without virtual functions :
A limited record is required for C that includes all members of P in order and its own members after
- [ ] C inherits from P with C introducing a virtual function (P does not have a virtual function):
C is a tagged limited record that includes all members of P in order and its own after
- [ ] C inherits from P with P having a virtual function:
C is a tagged limited record that inherits from P

All of these cases are recursive. So if C inherits from P with introduces virtual functions and inherits from O which does not have virtual functions P needs to include all members of O but C only needs to inherit from P in Ada.

Furthermore Ada does not support multiple inheritance so this probably won't be supported.

**Comment by senier** [comment]
Multiple inheritance is possible, [here](https://www.adacore.com/gems/gem-60-generating-ada-bindings-for-c-headers) is an example. We should check how/if/when interfaces are useful.

**Comment by jklmnn** [comment]
But as far as I can see this only works if all except one of the parents are pure virtual. So we would have to check that. I'm not sure if this works with non-virtual classes.

**Comment by jklmnn** [comment]
Multiple inheritance is done in #23.
