### ISSUE TITLE
Implement frontend tool

### ISSUE THREAD

**Issue by senier** [Componolit/capdpa#31]
Build a tool using the binding generator library. As arguments the tool receives:

- Output directory
- Project name
- A separator (--)
- Clang arguments

**Comment by jklmnn** [comment]
The clang parser only parses [one translation unit](https://github.com/llvm-mirror/clang/blob/8029b38886dd239769e3501dac21438e16886ce8/bindings/python/clang/cindex.py#L2687) at a time. Calling the tool with multiple files would then mean that there are two lists of arguments of undetermined length. I would propose to pass the clang arguments comma separated, so a call would look like this:
`parser.py -o . -p Capdpa -c -x,c++ header1.h header2.h`

**Comment by senier** [comment]
No sure I understand you suggestion. Is `-x` the clang specific option? What does -c mean? Where would include paths go?

**Comment by jklmnn** [comment]
`-c` is the clang switch that takes all clang arguments. `-x` is clang specific, so `-x,c++` would be like a call to `clang -x c++`.

**Comment by senier** [comment]
As the header files are our own arguments, we should keep them separate from Clang arguments. Also, I find the `-c` argument non-intuitive. Handling Clang argument manually (i.e. not with argparse) avoids escaping of whitespace. Your call could look like this:

```
parser.py -o . -p Capdpa header1.h header2.h -- -x,c++
```

In the frontend, just search "--" in sys.argv, pass the left part to argparse and the right part to Clang directly.
