### ISSUE TITLE
Research details of C++ class member layout

### ISSUE THREAD

**Issue by senier** [Componolit/capdpa#4]
We need the detailed layout of the C++ class we are handling to generate the corresponding representation clause of the Ada tagged type representing the class. To create this, we need to know how:

1. Variables interleaved with methods are treated
2. How padding is applied for small class members
3. How the size and location of a complex member variable (class, struct) is determined
4. How we determine the size/offset of class members in libclang

**Comment by jklmnn** [comment]
The spec states that
> Nonstatic data members of a (non-union) class with the same access control (Clause 11) are allocated so that later members have higher addresses within a class object. The order of allocation of non-static data members with different access control is unspecified (11).

And that padding between members can appear. The actual alignment itself is up to the implementation.

There is a clang flag `-fdump-record-layouts` that should show the class layout yet I was not able to get any information out of it at all. There is a [forum thread](http://clang-developers.42468.n3.nabble.com/Clang-3-4-fdump-record-layouts-not-producing-any-results-td4036285.html) that suggests using `-emit-llvm-only` but that didn't change anything. It ends with the statement that the `-cc1` flags are not documented.

For GCC there is `-fdump-class-hierarchy` which creates a file yet it only shows the classes size and alignment but not its members.

**Comment by jklmnn** [comment]
Ada records that refer to C++ classes must be `limited` and not `tagged`. A `tagged limited` record will not align correctly to the C++ class.
The tag is a 64bit (32bit for x86_32) value at the beginning of each record.
```
type R is
tagged limited record
   V : Integer;
end record;
for R use record
   V at 0 range 0 .. 31;
end record;
```
will yield
```
component overlaps tag field of "R"
```
Vs offset needs to be at least 8 (4 for x86_32) in this case.

**Comment by jklmnn** [comment]
Also the alignment and padding of member variables done by GNAT seems to be correct but all variables (including private ones) need to be specified in the record.
@senier the reason the private float on our test did not cause any problems was that it happened to be placed inside 32bit of padding. Reordering the members to remove that padding causes erroneous values.

**Comment by senier** [comment]
If we generate all class members - including private ones - how do we protect from invalid access to private members in Ada code?

**Comment by jklmnn** [comment]
An idea would be a private null record with the correct size. I tested it and it compiles:
```
package Parent is

   type Field64 is private;

private

   type Field64 is null record
      with Size => 64;

end Parent;
```
```
package Parent.Child is

   type Members is record
      Int : Integer;
      Prv : Parent.Field64;
   end record;

end Parent.Child;
```

While `Int` can be used easily and `Prv` is of course still visible it cannot be assigned a value. Doing an assignment in either direction will fail as it is not type conformant. Also since it is a null record it does not use any of the memory and therefore cannot have any value that could be read or written (gprbuild even issues a warning that all 64 bytes are unused). To clarify that this field is not intended for use we could add a `Private_` infront of each name. Since it should only exist in the autogenerated code and not be used a clumsy name shouldn't be a problem.

The only other option I see is calculating the sizes and offsets manually. But I'm not sure if this is really the best method since it both requires more effort and is probably more error prone.

**Comment by jklmnn** [comment]
Thinking a little about this it comes with the inconvenience of a splitted type declaration that is hard to fit within our current code generation model. Furthermore we still need to know the size.
Another approach would be to make this type public but keep it as a null record. Then it would be usable but would still have no value.
To fix the Value we could generate a corresponding private type to each type we have and automatically give each private variable the private type. I had something like this in mind:
```
package P is
   type Unsigned_32 is mod 2**32;
   type Private_Unsigned_32 is null record
      with Size => Unsigned_32'Size;

   type Class is record
      Public_Member : Unsigned_32;
      Private_Member : Private_Unsigned_32;
   end record;
end P;
```
This seems to be much easier to generate to me and would still prevent anyone from accessing the actual value. This would't work against an unchecked conversion of the private type, but omitting private fields completely doesn't do so either.

**Comment by jklmnn** [comment]
Instead of generating private types for each type, the private type is always and only declared in front of the containing record. It is also prefixed with the Class name of the record.
```
package P is
   type P_Private_Unsigned_32 is null record
      with Size => Unsigned_32'Size;

   type Class is record
      Public_Member : Unsigned_32;
      Private_Member : P_Private_Unsigned_32;
   end record;
end P;
```
