### ISSUE TITLE
Define the internal data structures of Python package

### ISSUE THREAD

**Issue by senier** [Componolit/capdpa#5]
During processing, we first need to collect information about existing namespaces and classes. Define the data structures for:

1. A class 
   * member variables
   * methods
   * constructors
   * parent classes
2. The class hierarchy (with namespace)
3. Namespaces (with classes and constants)

**Comment by senier** [comment]
In the [enum class](https://github.com/Componolit/capdpa/blob/ada_generator/capdpa/CXX/cxx_enum.py#L4) we define an enum as a set of constants with a name. How about unnamed enums?

**Comment by senier** [comment]
How are destructors handled in Ada bindings? Do we need to take care of those?

**Comment by jklmnn** [comment]
Unnamed enums are grouped together in the constants list. Their single constants need to be assigned an value while it is still known in which enum they reside in which order. After doing this the information about unnamed enums should not be relevant anymore.

I currently don't know how they are handled. Do we actually need them? This would only be the case if we are the ones calling them, otherwise they don't need to be accessible from Ada.

**Comment by senier** [comment]
OK, so no special handling for anonymous enums (only what's necessary for constants anyways).

When thinking about it, binding the destructor really shouldn't be necessary as we don't need to replace the implementation in Ada and it should be called automatically.

**Comment by senier** [comment]
As of the current data type definition, is looks like only namespaces contain constants and enums. Is that true, what if a C++ enum is defined inside a class - shouldn't that be added to the respective package for the class?

**Comment by jklmnn** [comment]
That is true, I'll add this.

**Comment by senier** [comment]
No need, I'm restructuring anyways. Just wanted to make sure I got this right. Thanks!

**Comment by senier** [comment]
We should discuss that. While a better separation would indeed be desirable, all the serialization would need to be done in explicit function calls. I could imagine this to get very ugly. When adding a serialization method to the class, the object can hide the details on how to serialize to Ada code and call serialization methods of its sub-objects to do that. I don't see how this could be accomplished when passing the C++ objects to a separate Ada package?

**Comment by jklmnn** [comment]
Well, it doesn't need to be separate function calls, but the C++ package could import the Ada package which defines these functions and provide them in its own objects. E.g.:
```
import Ada

Class CXX:

    to_ada(self):
        return Ada.convert(self)
```
Something like this.

**Comment by senier** [comment]
But then we'd either add the `to_ada` method to the common base class and dispatch on the object type or add it to every class in `cxx` and call a specific conversion function. I don't see the benefit here compared to writing the conversion function into the `cxx_*` classes directly. Either way the parts are tightly coupled and we cannot change the implementation without rewriting the code.

We should discuss that on Monday together with @treiher.

**Comment by jklmnn** [comment]
The internal data structure is going to be renamed into `IR`
